### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by EmmettMorehouse** [cmehring/GH-Studios#2]
Home page for app, with information and login area.

**Comment by Greenhxwk** [comment]
So are we allowed to use CSS for the website as well? I keep forgetting

**Comment by EmmettMorehouse** [comment]
Why couldn't we, did he say that in class? I think we can do pretty much anything for the 'appearance' part.

**Comment by ChrisDesigns** [comment]
Bigger ticket item, base for main page main. Content + further design needed

**Comment by Greenhxwk** [comment]
> Bigger ticket item, base for main page main. Content + further design needed

I'll make a sleek design landing page at some point this or next week
