### ISSUE TITLE
Design site layout via Photoshop, Illustrator etc

### ISSUE THREAD

**Issue by Greenhxwk** [cmehring/GH-Studios#8]
That's if we're allowed to use CSS and whatnot. I feel the website should have a minimalist type layout.

- [x] Landing Page Design
- [x] Timeline Page design
- [x] Dasboard Page design

**Comment by ChrisDesigns** [comment]
My work uses https://zeplin.io/ it seems to be pretty nice. A tool that allows you to use css while designing. However, it should be noted: we should try to use some sort of design. Such as https://material.io/design/
